name: Lint

on: [push, pull_request]

jobs:
  fmt:
    name: Code Format
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:latest
    steps:
      - uses: actions/checkout@main
      - run: terraform fmt --recursive -check
